version: '3'

services:
  database:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: lampstack
       MYSQL_USER: user
       MYSQL_PASSWORD: user

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    ports:
      - 4901:80
    environment:
       PMA_USER: root
       PMA_PASSWORD: root
       PMA_HOSTS: database
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: user
       MYSQL_PASSWORD: user

  website:
    build: .
    volumes:
      - ./workspace:/var/www/html
    restart: always
    ports:
      - 4900:80
    links:
      - database
    depends_on:
      - database   
